spring:
  application:
    name: nequi
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin


logging:
  level:
    org.springframework.r2dbc: DEBUG
